### ISSUE TITLE
Feature request: consider adding support for pprof-rs

### ISSUE THREAD

**Issue by gww-parity** [aclysma/profiling#11]
Could you consider adding support for pprof-rs:

https://lib.rs/crates/pprof
https://github.com/tikv/pprof-rs

or do you consider it does not add benefit to existing collection?

**Comment by aclysma** [comment]
Does it do instrumented profiling? It appears to be a sampling profiler, so it automatically works without needing to decorate code with profiling::scope!() macros.

**Comment by gww-parity** [comment]
Correct!
My mistake.
Thank you!
/close
