### ISSUE TITLE
Compilation fails with procmacro feature off

### ISSUE THREAD

**Issue by cwfitzgerald** [aclysma/profiling#12]
On lib.rs:86 there's an unconditional import of the proc macro function that causes builds to fail with proc macros off.

**Comment by aclysma** [comment]
Thanks! I'm going to leave the issue open until 1) new version is published 2) CI is testing this

**Comment by aclysma** [comment]
Published as 0.1.10, CI should catch this if the regresses in the future. Thanks for reporting it!

**Comment by cwfitzgerald** [comment]
Thanks for the quick publish!
