### ISSUE TITLE
`optick.dev` leads to an invalid/suspended page

### ISSUE THREAD

**Issue by Dreamykass** [aclysma/profiling#14]
This link <https://optick.dev/>, in here <https://github.com/aclysma/profiling#optick>, leads to a `"This Account has been suspended."` page.

**Comment by Dreamykass** [comment]
Could probably just be changed to link to <https://github.com/bombomby/optick> instead

**Comment by aclysma** [comment]
Thanks for mentioning, if it's still broken after a few days that sounds like a good way to go!

**Comment by aclysma** [comment]
Made the suggested change, thanks again for mentioning it. I'm planning to 1.0 this crate soon, which will update the link on crates.io
