### ISSUE TITLE
Use `tracy-client` directly

### ISSUE THREAD

**Issue by Imberflur** [aclysma/profiling#2]
As mentioned in the readme there is overhead with going through `tracing`. Iirc when I measured it, it was on the order of hundreds of ns.

Of course, I think it would make sense to keep the `tracing` backend since that allows the instrumentation to be used for other things using `tracing`.

**Comment by aclysma** [comment]
I think that would be a good change too! I think the main reason I didn't do it that way was because all the examples I saw from the crate went through tracing. Would be happy to accept a PR for this, or might get around to doing it myself at some point.

**Comment by aclysma** [comment]
I'll leave this open until 0.1.6 is published

**Comment by aclysma** [comment]
This is published now in 0.1.6 though I re-published as 0.1.7 because I forgot to bump the procmacro crate version
