### ISSUE TITLE
Tracy freezes when `simple` example is run with admin rights

### ISSUE THREAD

**Issue by Boscop** [aclysma/profiling#20]
I'm running the `simple` example on Win 8.1, and when I run it without admin rights, it works, but then I can't use the sampling profiling method.
When I run simple.exe with admin rights (as the tracy manual says, for getting sampling-based profiling), as soon as I connect Tracy to it, simple.exe and Tracy both seem to "soft-freeze", i.e. Tracy is not updating its UI with any data but its UI stays responsive, and simple.exe is not printing any more lines to stdout, and only using 2.5% CPU compared to the 12.5% it was using before connecting Tracy to it.
Why is this happening?
I want to get the sampling profiling method working.

**Comment by aclysma** [comment]
I think this is better directed tracy (https://github.com/wolfpld/tracy) or the tracy_client crate (https://github.com/nagisa/rust_tracy_client). 

That said, you might be running into this, which is unfortunately affecting a lot of people.
https://developercommunity.visualstudio.com/t/No-Data-in-CPU-Usage-Tool-Windows-Updat/1384519#T-N1402413

**Comment by Boscop** [comment]
Hm, can it really be that issue, considering that ETW sampling is working via Optick and UIforETW?

Also that OP writes
> Issue: Recently a Windows Update broke the CPU Usage tool in Visual Studio where no data is collected.

I'm not on Win 10 but 8.1, so I probably don't have that update that broke it for them?

**Comment by aclysma** [comment]
For problems with sampled profiling with tracy, I would raise an issue here: https://github.com/wolfpld/tracy
