### ISSUE TITLE
Expose thread name setter?

### ISSUE THREAD

**Issue by rksm** [aclysma/profiling#43]
Hi, thanks for this library, it is great!

Since some of profiling utilities have a way to specify the thread name, would it make sense to expose a common setter in the profiling API? This would save some boilerplate when using it.

**Comment by aclysma** [comment]
Glad it’s working well for you!

Does the api in this example do what you are looking for?
https://github.com/aclysma/profiling/blob/958fa8cf42a1f2687c69467ea93c113176a12071/examples/simple.rs#L28

I think some profiling APIs require the name at the start and can’t change it, but I may be misremembering.

Also, calling directly into the profiling backed you want to use is allowed. But I agree, naming a thread seems simple and universal.

**Comment by aclysma** [comment]
Going to close this since the thread is inactive, hopefully the API I mentioned above is sufficient.
