### ISSUE TITLE
Wrapping an extern "C" function

### ISSUE THREAD

**Issue by ewpratten** [aclysma/profiling#50]
I would like to be able to profile some `extern "C"` functions.

Currently, if I try to apply the `#[profiling::function]` macro to one of these functions, I get an error:

```rust
extern "C" {
    #[profiling::function]
    pub fn MyFunction(x: Data);
}
```

```text
error: expected curly braces
```

Is there any way to do this without wrapping every external function in a Rust function first?

**Comment by aclysma** [comment]
The way the procmacro works is it appends a one-liner to the code in the body of the function. An extern function doesn't have a body, so we can't really inject new behavior into it. I suspect any solution for this would ultimately behind the scenes just wrap the call in a rust function.

I try to keep procmacros extremely straightforward and use them sparingly, and I think the cost/benefit ratio for this would be outside my comfort zone. (I'd keep an open mind if you wanted to give it a try though.)

**Comment by ewpratten** [comment]
Ah, I figured.

I'm going to try auto-wrapping the functions then.

**Comment by aclysma** [comment]
Since this has been idle for a while and I'm not optimistic a solution would be simple, going to close.
