### ISSUE TITLE
Update Puffin to 0.17; use puffin-egui in examples?

### ISSUE THREAD

**Issue by ids1024** [aclysma/profiling#58]
The latest version of Puffin is now 0.17.

The example uses puffin-imgui, which has been removed (https://github.com/EmbarkStudios/puffin/pull/140) in favor of puffin-egui. So I guess the examples will need to be updated.

**Comment by aclysma** [comment]
Yeah, if you want a local build that just works, there's a decent chance you could just bump the version number and it would be fine. I just don't like publishing untested code, so I'd really prefer to update the examples first.

**Comment by aclysma** [comment]
I've rewritten the example to use eframe/egui in this branch https://github.com/aclysma/profiling/tree/new-puffin-example

If it passes CI I'll integrate. Latest version of puffin is now 0.18, I also updated to that version.

**Comment by aclysma** [comment]
1.0.12 has been published
