### ISSUE TITLE
`function` proc macro break some clippy lints

### ISSUE THREAD

**Issue by gwen-lg** [aclysma/profiling#75]
Use of #[profiling::function] shouldn't break Clippy lint detection like  [`missing_errors_doc`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_errors_doc).

Currently, this report no lint
```rust
/// This `profiling::function` attribute is equivalent to profiling::scope!(function_name)
#[profiling::function]
fn some_function() -> Result<(), Error>{
    burn_time(5)?;
}
```

while, this report `missing_errors_doc` lint
```rust
fn some_function() -> Result<(), Error>{
    profiling::scope!(function_name)
    burn_time(5)?;
}
```

**Comment by aclysma** [comment]
As far as I can tell, the macro is passing through doc comments. This seems like expected behavior if this lint is enabled (although I don't think it typically is for non-public functions.)

**Comment by gwen-lg** [comment]
I'm not sure I made myself understood.

I don't want having the `#[profiling::function]` marker to cause me to not have an error reported by the `missing_errors_doc` lint, while if I remove the marker I have an error reported.
While currently, the lint [missing_errors_doc](https://rust-lang.github.io/rust-clippy/master/index.html#missing_errors_doc) is not reported as expected when the marker `#[profiling::function]` is set on a function.

Note: I don't understand what you talking about with `passing through doc comments`.

**Comment by gwen-lg** [comment]
I have create a demo project here : https://github.com/gwen-lg/clippy-lints-doc-tests
